config/routes.rb
Lottery::Application.routes.draw do
  
  resources :orders

  resources :consumers

  resources :tickets

  resources :bussinesses

  resources :rewards
  
  resources :activities do
    resources :rewards
    resources :tickets
  end

  devise_for :users, :controllers => { :sessions => "sessions" }

  get '/consumer/login', to: 'consumer/sessions#create'
  get '/consumer/logout', to: 'consumer/sessions#destroy'
  get '/consumer/buy', to: 'consumer/orders#create'
  get '/consumer/exchange', to: 'consumer/tickets#exchange'
  get '/consumer/activities', to: 'consumer/activities#index'
  get '/consumer/change_profile', to: 'consumer/consumers#update'
  get '/consumer/lottery', to: 'consumer/tickets#lottery'
  get '/consumer/tickets', to: 'consumer/tickets#index'
  get '/consumer/buy_lottery', to: 'consumer/consumers#buy_lottery_count'
  get '/consumer/lottery_count', to: 'consumer/consumers#lottery_count'

  root :to => "welcome#index"
  
end

app/models/reward.rb
class Reward < ActiveRecord::Base

  belongs_to :activity
  belongs_to :bussiness
  has_attached_file :photo_url, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/assets/missing_reward.jpg"
  validates_attachment :photo_url, content_type: { content_type: "image/jpg" }

  def left_amount 
    0
  end

  def info
    {
      id: id, name: name, desc: desc  
    }
  end
  
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :set_reward, only: [:show, :edit, :update, :destroy]
  before_action :find_activity, only: [:index, :new]
  # GET /rewards
  # GET /rewards.json
  def index
    @rewards = @activity.rewards
  end

  # GET /rewards/1
  # GET /rewards/1.json
  def show
    @activity = @reward.activity
  end

  # GET /rewards/new
  def new
    @reward = Reward.new
  end

  # GET /rewards/1/edit
  def edit
    @activity = @reward.activity
  end

  # POST /rewards
  # POST /rewards.json
  def create
    @activity = Activity.find(params[:reward][:activity_id])
    @reward = Reward.new(reward_params)
    respond_to do |format|
      if @reward.save
        format.html { redirect_to @reward, notice: 'Reward was successfully created.' }
        format.json { render action: 'show', status: :created, location: @reward }
      else
        format.html { render action: 'new' }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rewards/1
  # PATCH/PUT /rewards/1.json
  def update
    respond_to do |format|
      if @reward.update(reward_params)
        format.html { redirect_to @reward, notice: 'Reward was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rewards/1
  # DELETE /rewards/1.json
  def destroy
    @activity = @reward.activity
    @reward.destroy
    respond_to do |format|
      format.html { redirect_to activity_rewards_path(@activity) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reward
      @reward = Reward.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reward_params
      params.require(:reward).permit(:activity_id, :name, :desc, :photo, 
        :amount, :photo_url, :bussiness_id, :rate, :used_time, :is_used)
    end

    def find_activity
      @activity = Activity.find(params[:activity_id])
    end

end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= content_for :head do %>

  <link rel="stylesheet" href="/assets/css/jquery-ui-1.10.3.custom.min.css">
  <link rel="stylesheet" href="/assets/css/chosen.css">
  <link rel="stylesheet" href="/assets/css/datepicker.css">
  <link rel="stylesheet" href="/assets/css/bootstrap-timepicker.css">
  <link rel="stylesheet" href="/assets/css/daterangepicker.css">
  <link rel="stylesheet" href="/assets/css/colorpicker.css">

  <script src="/assets/js/jquery-ui-1.10.3.custom.min.js"></script>
  <script src="/assets/js/jquery.ui.touch-punch.min.js"></script>
  <script src="/assets/js/chosen.jquery.min.js"></script>
  <script src="/assets/js/fuelux/fuelux.spinner.min.js"></script>
  <script src="/assets/js/date-time/bootstrap-datepicker.min.js"></script>
  <script src="/assets/js/date-time/bootstrap-timepicker.min.js"></script>
  <script src="/assets/js/date-time/moment.min.js"></script>
  <script src="/assets/js/date-time/daterangepicker.min.js"></script>
  <script src="/assets/js/bootstrap-colorpicker.min.js"></script>
  <script src="/assets/js/jquery.knob.min.js"></script>
  <script src="/assets/js/jquery.autosize-min.js"></script>
  <script src="/assets/js/jquery.inputlimiter.1.3.1.min.js"></script>
  <script src="/assets/js/jquery.maskedinput.min.js"></script>
  <script src="/assets/js/bootstrap-tag.min.js"></script>

  <script type="text/javascript">
  </script>

<% end -%>

<div class="widget-box">
  <div class="widget-header">
    <h4>
      奖品
    </h4>
  </div>

  <div class="widget-body">
    <div class="widget-main no-padding">
      <%= form_for(@reward, :html => { :multipart => true })  do |f| %>

      <fieldset>
        <%= f.hidden_field :activity_id, :value => @activity.id %>
        <%= f.label :name, "名称" %>
        <%= f.text_field :name %>

        <%= f.label :desc, "简介" %>
        <%= f.text_field :desc %>

        <%= f.label :address, "地址" %>
        <%= f.text_field :address %>

        <%= f.label :conversion_time, "兑换时间" %>
        <%= f.text_field :conversion_time %>

        <%= f.label :bussiness_id, "商家" %>
        <%= f.select :bussiness_id, options_from_collection_for_select(Bussiness.all, :id, :name) %>

        <%= f.label :amount, "数量" %>
        <%= f.text_field :amount %>

        <%= f.label :rate, "概率" %>
        <%= f.text_field :rate %>

        <%= f.label :photo_url, "上传照片" %>
        <%= f.file_field :photo_url %>        

      </fieldset>

      <div class="form-actions center">
        <button class="btn btn-small btn-success">
          提交 <i class="icon-arrow-right icon-on-right bigger-110"></i>
        </button>
      </div>
    <% end -%>
  </div>
</div>
</div>

app/views/rewards/edit.html.erb
<div class="breadcrumbs" id="breadcrumbs">
  <ul class="breadcrumb">
    <li>
      <i class="icon-home home-icon"></i>
      <a href="#">活动管理</a>

      <span class="divider">
        <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>

    <li>
      <i class="icon-home home-icon"></i>
      <%= link_to @activity.name, @activity %>
      <span class="divider">
        <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>

    <li>
      <i class="icon-home home-icon"></i>
      <%= link_to @reward.name, @reward %>
      <span class="divider">
        <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>
    <li class="active">
      编辑
    </li>
  </ul>
</div>

<div class="page-content">

  <a href="<%= activity_rewards_path(@activity)%>" class="btn btn-app btn-pink btn-mini">
    <i class="icon-share-alt small-125"></i>
  </a>

  <h3 class="header smaller lighter green"></h3>                    

<%= render 'form' %>



</div>

app/views/rewards/index.html.erb
<div class="breadcrumbs" id="breadcrumbs">
  <ul class="breadcrumb">
    <li> <i class="icon-home home-icon"></i>
      <a href="<%= activities_path%>">活动管理</a>

      <span class="divider"> <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>
    <li> <i class="icon-home home-icon"></i>
      <a href="<%= activity_path(@activity) %>"><%= @activity.name%></a>

      <span class="divider"> <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>
    <li class="active">奖品</li>
  </ul>
</div>

<div class="page-content">

  <a href="<%= new_activity_reward_path(@activity) %>
    " class="btn btn-app btn-primary no-radius btn-small">
    <i class="icon-edit small-125"></i>
    新奖品
  </a>

  <h3 class="header smaller lighter green"></h3>

  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>名称</th>
        <th>简介</th>
        <th>商家</th>
        <th>数量</th>
        <th>剩余</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @rewards.each do |reward| %>
      <tr>
        <td>
          <%= reward.name %></td>
        <td>
          <%= reward.desc %></td>
        <td><%= reward.bussiness.name%></td>
        <td><%= reward.amount %></td>
        <td><%= reward.left_amount %></td>
        <td>
          <div class="hidden-phone visible-desktop btn-group">
            <a href="<%= reward_path(reward)%>" class="btn btn-mini btn-success">
              <i class="icon-ok bigger-120"></i>
            </a>

            <a href="<%= edit_reward_path(reward) %>" class="btn btn-mini btn-info">
              <i class="icon-edit bigger-120"></i>
            </a>

            <%= link_to reward, method: :delete, :class => "btn btn-mini btn-danger", data: { confirm: '确定删除?' } do %> 
              <i class="icon-trash bigger-120"></i>
            <% end -%>
          </div>

        </td>

  <% end %></tbody>
</table>

<br></div>

app/views/rewards/new.html.erb
<div class="breadcrumbs" id="breadcrumbs">
  <ul class="breadcrumb">
    <li>
      <i class="icon-home home-icon"></i>
      <%= link_to "活动管理", activities_path%>

      <span class="divider">
        <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>
    <li class="active">
      添加奖品
    </li>
  </ul>
</div>

<div class="page-content">

  <a href="<%= activity_rewards_path(@activity)%>" class="btn btn-app btn-pink btn-mini">
    <i class="icon-share-alt small-125"></i>
  </a>

  <h3 class="header smaller lighter green"></h3>                    

<%= render 'form' %>



</div>

app/views/rewards/show.html.erb
<div class="breadcrumbs" id="breadcrumbs">
  <ul class="breadcrumb">
    <li>
      <i class="icon-home home-icon"></i>
      <%= link_to "活动管理", activities_path %>

      <span class="divider">
        <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>
    <li>
      <i class="icon-home home-icon"></i>
      <%= link_to @activity.name, @activity %>
      <span class="divider">
        <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>
    <li class="active">
      <%= @reward.name%>
    </li>
  </ul>
</div>

<div class="page-content">

  <a href="<%= activity_path(@activity) %>" class="btn btn-app btn-pink btn-mini">
    <i class="icon-share-alt small-125"></i>
  </a>

  <a href="<%= edit_reward_path(@reward) %>
    " class="btn btn-app btn-primary  btn-mini">
    <i class="icon-edit small-125"></i>
  </a>

  <h3 class="header smaller lighter green"></h3>                    


  <p>
    <strong>名称:</strong>
    <%= @reward.name %>
  </p>

  <p>
    <strong>简介:</strong>
    <%= @reward.desc %>
  </p>

  <p>
    <strong>最大数量:</strong>
    <%= @reward.amount %>
  </p>

  <p>
    <strong>剩余:</strong>
    <%= @reward.amount %>
  </p>

  <p>
    <%= image_tag @reward.photo_url.url(:medium) %>
  </p>



</div>