config/routes.rb
Lottery::Application.routes.draw do
  
  resources :orders

  resources :consumers

  resources :tickets

  resources :bussinesses

  resources :rewards
  
  resources :activities do
    resources :rewards
    resources :tickets
  end

  devise_for :users, :controllers => { :sessions => "sessions" }

  get '/consumer/login', to: 'consumer/sessions#create'
  get '/consumer/logout', to: 'consumer/sessions#destroy'
  get '/consumer/buy', to: 'consumer/orders#create'
  get '/consumer/exchange', to: 'consumer/tickets#exchange'
  get '/consumer/activities', to: 'consumer/activities#index'
  get '/consumer/change_profile', to: 'consumer/consumers#update'
  get '/consumer/lottery', to: 'consumer/tickets#lottery'
  get '/consumer/tickets', to: 'consumer/tickets#index'
  get '/consumer/buy_lottery', to: 'consumer/consumers#buy_lottery_count'
  get '/consumer/lottery_count', to: 'consumer/consumers#lottery_count'

  root :to => "welcome#index"
  
end

app/controllers/bussinesses_controller.rb
class BussinessesController < ApplicationController
  before_action :set_bussiness, only: [:show, :edit, :update, :destroy]

  # GET /bussinesses
  # GET /bussinesses.json
  def index
    @bussinesses = Bussiness.all
  end

  # GET /bussinesses/1
  # GET /bussinesses/1.json
  def show
  end

  # GET /bussinesses/new
  def new
    @bussiness = Bussiness.new
  end

  # GET /bussinesses/1/edit
  def edit
  end

  # POST /bussinesses
  # POST /bussinesses.json
  def create
    @bussiness = Bussiness.new(bussiness_params)

    respond_to do |format|
      if @bussiness.save
        format.html { redirect_to @bussiness, notice: 'Bussiness was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bussiness }
      else
        format.html { render action: 'new' }
        format.json { render json: @bussiness.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bussinesses/1
  # PATCH/PUT /bussinesses/1.json
  def update
    respond_to do |format|
      if @bussiness.update(bussiness_params)
        format.html { redirect_to @bussiness, notice: 'Bussiness was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bussiness.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bussinesses/1
  # DELETE /bussinesses/1.json
  def destroy
    @bussiness.destroy
    respond_to do |format|
      format.html { redirect_to bussinesses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bussiness
      @bussiness = Bussiness.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bussiness_params
      params.require(:bussiness).permit(:name, :join_time)
    end
end

app/helpers/bussinesses_helper.rb
module BussinessesHelper
end

app/views/bussinesses/_form.html.erb
<%= content_for :head do %>
<link rel="stylesheet" href="/assets/css/jquery-ui-1.10.3.custom.min.css">
<link rel="stylesheet" href="/assets/css/chosen.css">
<link rel="stylesheet" href="/assets/css/datepicker.css">
<link rel="stylesheet" href="/assets/css/bootstrap-timepicker.css">
<link rel="stylesheet" href="/assets/css/daterangepicker.css">
<link rel="stylesheet" href="/assets/css/colorpicker.css">

<script src="/assets/js/jquery-ui-1.10.3.custom.min.js"></script>
<script src="/assets/js/jquery.ui.touch-punch.min.js"></script>
<script src="/assets/js/chosen.jquery.min.js"></script>
<script src="/assets/js/fuelux/fuelux.spinner.min.js"></script>
<script src="/assets/js/date-time/bootstrap-datepicker.min.js"></script>
<script src="/assets/js/date-time/bootstrap-timepicker.min.js"></script>
<script src="/assets/js/date-time/moment.min.js"></script>
<script src="/assets/js/date-time/daterangepicker.min.js"></script>
<script src="/assets/js/bootstrap-colorpicker.min.js"></script>
<script src="/assets/js/jquery.knob.min.js"></script>
<script src="/assets/js/jquery.autosize-min.js"></script>
<script src="/assets/js/jquery.inputlimiter.1.3.1.min.js"></script>
<script src="/assets/js/jquery.maskedinput.min.js"></script>
<script src="/assets/js/bootstrap-tag.min.js"></script>

<script type="text/javascript">
    ready = function($){
      $('.date-picker').datepicker()
    }; 
    jQuery(ready);

    jQuery(function ($) {
      $(document).on('page:load', ready);  
    });
    


  </script>

<% end -%>

<div class="widget-box">
  <div class="widget-header">
    <h4>商家</h4>
  </div>

  <div class="widget-body">
    <div class="widget-main no-padding">
      <%= form_for(@bussiness) do |f| %>
      <!--<legend>Form</legend>
    -->
    <fieldset>
      <%= f.label :name, "名称" %>
      <%= f.text_field :name %>
      <!-- <span class="help-block">Example block-level help text here.</span>
    -->
    <%= f.label :join_time, "加入时间" %>

    <div class="row-fluid input-append">
      <%= f.text_field :join_time, :class =>
      "date-picker", :id => "id-date-picker-1", :type => "text", "data-date-format" => "yyyy-mm-dd" %>
      <span class="add-on"> <i class="icon-calendar"></i>
      </span>
    </div>
    <!-- <span class="help-block">Example block-level help text here.</span>
  -->
</fieldset>

<div class="form-actions center">
  <button class="btn btn-small btn-success">
    提交 <i class="icon-arrow-right icon-on-right bigger-110"></i>
  </button>
</div>
<% end -%></div>
</div>
</div>

app/views/bussinesses/edit.html.erb
<div class="breadcrumbs" id="breadcrumbs">
  <ul class="breadcrumb">
    <li>
      <i class="icon-home home-icon"></i>
      <%= link_to "商家管理", bussinesses_path %>

      <span class="divider">
        <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>
    <li>
      <i class="icon-home home-icon"></i>
      <%= link_to @bussiness.name, @bussiness %>

      <span class="divider">
        <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>
    <li class="active">
      编辑
    </li>
  </ul>
</div>

<div class="page-content">

  <a href="<%= bussinesses_path%>" class="btn btn-app btn-pink btn-mini">
    <i class="icon-share-alt small-125"></i>
  </a>

  <h3 class="header smaller lighter green"></h3>                    

<%= render 'form' %>



</div>

app/views/bussinesses/index.html.erb
<div class="breadcrumbs" id="breadcrumbs">
  <ul class="breadcrumb">
    <li> <i class="icon-home home-icon"></i>
      <%= link_to "商家管理", bussinesses_path %>
      <span class="divider"> <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>
    <li class="active">总览</li>
  </ul>
</div>

<div class="page-content">

  <a href="<%= new_bussiness_path %>
    " class="btn btn-app btn-primary no-radius btn-small">
    <i class="icon-edit small-125"></i>
    新商家
  </a>

  <h3 class="header smaller lighter green"></h3>

  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>名称</th>
        <th>加入时间</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @bussinesses.each do |bussiness| %>
      <tr>
        <td>
          <%= bussiness.name %></td>
        <td>
          <%= bussiness.join_time %></td>
        <td>
          <div class="hidden-phone visible-desktop btn-group">
            <a href="<%= bussiness_path(bussiness)%>" class="btn btn-mini btn-success">
              <i class="icon-ok bigger-120"></i>
            </a>

            <a href="<%= edit_bussiness_path(bussiness) %>" class="btn btn-mini btn-info">
              <i class="icon-edit bigger-120"></i>
            </a>

            <%= link_to bussiness, method: :delete, :class => "btn btn-mini btn-danger", data: { confirm: '确定删除?' } do %> 
              <i class="icon-trash bigger-120"></i>
            <% end -%>
          </div>

        </td>
  <% end %></tbody>
</table>

<br></div>

app/views/bussinesses/new.html.erb
<div class="breadcrumbs" id="breadcrumbs">
  <ul class="breadcrumb">
    <li>
      <i class="icon-home home-icon"></i>
      <%= link_to "商家管理", bussinesses_path %>

      <span class="divider">
        <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>
    <li class="active">
      加入新商家
    </li>
  </ul>
</div>

<div class="page-content">

  <a href="<%= bussinesses_path%>" class="btn btn-app btn-pink btn-mini">
    <i class="icon-share-alt small-125"></i>
  </a>

  <h3 class="header smaller lighter green"></h3>                    

<%= render 'form' %>



</div>

app/views/bussinesses/show.html.erb
<div class="breadcrumbs" id="breadcrumbs">
  <ul class="breadcrumb">
    <li>
      <i class="icon-home home-icon"></i>
      <%= link_to "商家管理", bussinesses_path %>
      <span class="divider">
        <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>
    <li class="active">
      <%= @bussiness.name%>
    </li>
  </ul>
</div>

<div class="page-content">

  <a href="<%= bussinesses_path%>" class="btn btn-app btn-pink btn-mini">
    <i class="icon-share-alt small-125"></i>
  </a>

  <a href="<%= edit_bussiness_path(@bussiness) %>
    " class="btn btn-app btn-primary  btn-mini">
    <i class="icon-edit small-125"></i>
  </a>

  <h3 class="header smaller lighter green"></h3>                    

  <div class="well">
                      <h4 class="green smaller lighter">商家名称 </h4>
  <%= @bussiness.name %>
                      <h4 class="green smaller lighter">加入时间</h4>
                     
                        <%= @bussiness.join_time %>
                    </div>

</div>