config/routes.rb
Lottery::Application.routes.draw do
  
  resources :orders

  resources :consumers

  resources :tickets

  resources :bussinesses

  resources :rewards
  
  resources :activities do
    resources :rewards
    resources :tickets
  end

  devise_for :users, :controllers => { :sessions => "sessions" }

  get '/consumer/login', to: 'consumer/sessions#create'
  get '/consumer/logout', to: 'consumer/sessions#destroy'
  get '/consumer/buy', to: 'consumer/orders#create'
  get '/consumer/exchange', to: 'consumer/tickets#exchange'
  get '/consumer/activities', to: 'consumer/activities#index'
  get '/consumer/change_profile', to: 'consumer/consumers#update'
  get '/consumer/lottery', to: 'consumer/tickets#lottery'
  get '/consumer/tickets', to: 'consumer/tickets#index'
  get '/consumer/buy_lottery', to: 'consumer/consumers#buy_lottery_count'
  get '/consumer/lottery_count', to: 'consumer/consumers#lottery_count'

  root :to => "welcome#index"
  
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base

  belongs_to :activity
  belongs_to :reward
  belongs_to :consumer

  before_create do |ticket|
    ticket.uid = SecureRandom.uuid
  end

  def info
    {
      id: id, award: reward.info, coupon: uid, used_time: used_time  
    }
    
  end

end

app/controllers/consumer/tickets_controller.rb
class Consumer::TicketsController < Consumer::ApplicationController

  before_filter :authenticate_consumer!

  def index
    render json: {code: SUCCESS_CODE, tickets: current_consumer.tickets.map {|t| t.info}}
  end

  def exchange
    render json: {status: 'success'}
  end

  def lottery
    @activity = Activity.find(params[:activity_id])
    @ticket = @activity.lottery(current_consumer)
    render json: {code: SUCCESS_CODE, ticket: @ticket.info}
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  before_action :set_activity, only: [:index, :new]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @activity = @ticket.activity
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
    @activity = @ticket.activity
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ticket }
      else
        format.html { render action: 'new' }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:uid, :consumer_id, :reward_id, :used_time, :is_used, :activity_id)
    end

    def set_activity
      @activity = Activity.find(params[:activity_id])
    end
end

app/helpers/consumer/tickets_helper.rb
module Consumer::TicketsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= content_for :head do %>
<link rel="stylesheet" href="/assets/css/jquery-ui-1.10.3.custom.min.css">
<link rel="stylesheet" href="/assets/css/chosen.css">
<link rel="stylesheet" href="/assets/css/datepicker.css">
<link rel="stylesheet" href="/assets/css/bootstrap-timepicker.css">
<link rel="stylesheet" href="/assets/css/daterangepicker.css">
<link rel="stylesheet" href="/assets/css/colorpicker.css">

<script src="/assets/js/jquery-ui-1.10.3.custom.min.js"></script>
<script src="/assets/js/jquery.ui.touch-punch.min.js"></script>
<script src="/assets/js/chosen.jquery.min.js"></script>
<script src="/assets/js/fuelux/fuelux.spinner.min.js"></script>
<script src="/assets/js/date-time/bootstrap-datepicker.min.js"></script>
<script src="/assets/js/date-time/bootstrap-timepicker.min.js"></script>
<script src="/assets/js/date-time/moment.min.js"></script>
<script src="/assets/js/date-time/daterangepicker.min.js"></script>
<script src="/assets/js/bootstrap-colorpicker.min.js"></script>
<script src="/assets/js/jquery.knob.min.js"></script>
<script src="/assets/js/jquery.autosize-min.js"></script>
<script src="/assets/js/jquery.inputlimiter.1.3.1.min.js"></script>
<script src="/assets/js/jquery.maskedinput.min.js"></script>
<script src="/assets/js/bootstrap-tag.min.js"></script>

<script type="text/javascript">
    ready = function($){
      $('.date-picker').datepicker()
    }; 
    jQuery(ready);

    jQuery(function ($) {
      $(document).on('page:load', ready);  
    });
    


  </script>

<% end -%>

<div class="widget-box">
  <div class="widget-header">
    <h4>奖券 (<%= @ticket.uid %>)</h4>
  </div>

  <div class="widget-body">
    <div class="widget-main no-padding">
      <%= form_for(@ticket) do |f| %>
    <fieldset>
      <%= f.hidden_field :activity_id, :value => @activity.id %>

      <div class="field">
        <%= f.label :phone, "手机号" %><br>
        <%= f.text_field :phone %>
      </div>

      <div class="field">
        <%= f.label :reward_id, "奖品" %><br>
        <%= f.select :reward_id, options_from_collection_for_select(@activity.rewards, :id, :name) %>
      </div>

      <div class="field">
        <label class="pull-right">
        <%= f.check_box :is_used %>
        <span class="lbl">是否使用</span>
        </label>
      </div>
    <!-- <span class="help-block">Example block-level help text here.</span>
  -->
</fieldset>

<div class="form-actions center">
  <button class="btn btn-small btn-success">
    提交 <i class="icon-arrow-right icon-on-right bigger-110"></i>
  </button>
</div>
<% end -%></div>
</div>
</div>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<div class="breadcrumbs" id="breadcrumbs">
  <ul class="breadcrumb">
    <li> <i class="icon-home home-icon"></i>
      <%= link_to "活动管理", activities_path %>
      <span class="divider"> <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>

    <li> <i class="icon-home home-icon"></i>
      <%= link_to @activity.name, @activity %>
      <span class="divider"> <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>
    <li class="active">奖券</li>
  </ul>
</div>

<div class="page-content">

  <a href="<%= new_activity_ticket_path(@activity) %>
    " class="btn btn-app btn-primary no-radius btn-small">
    <i class="icon-edit small-125"></i>
    新奖券
  </a>

  <h3 class="header smaller lighter green"></h3>

  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>唯一编号</th>
        <th>领奖人</th>
        <th>是否兑换</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @tickets.each do |ticket| %>
      <tr>
        <td>
          <%= ticket.uid %></td>
        <td>
          <%= ticket.phone %></td>
        <td>
          <%= ticket.is_used %></td>
        <td>
          <div class="hidden-phone visible-desktop btn-group">
            <a href="<%= ticket_path(ticket)%>" class="btn btn-mini btn-success">
              <i class="icon-ok bigger-120"></i>
            </a>

            <a href="<%= edit_ticket_path(ticket) %>" class="btn btn-mini btn-info">
              <i class="icon-edit bigger-120"></i>
            </a>

            <%= link_to ticket, method: :delete, :class => "btn btn-mini btn-danger", data: { confirm: '确定删除?' } do %> 
              <i class="icon-trash bigger-120"></i>
            <% end -%>
          </div>

        </td>
  <% end %></tbody>
</table>

<br></div>

app/views/tickets/new.html.erb
<div class="breadcrumbs" id="breadcrumbs">
  <ul class="breadcrumb">
    <li>
      <i class="icon-home home-icon"></i>
      <%= link_to "活动管理", activities_path%>

      <span class="divider">
        <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>

    <li>
      <i class="icon-home home-icon"></i>
      <%= link_to @activity.name, @activity%>

      <span class="divider">
        <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>

    <li class="active">
      创建新奖券
    </li>
  </ul>
</div>

<div class="page-content">

  <a href="<%= activity_tickets_path(@activity)%>" class="btn btn-app btn-pink btn-mini">
    <i class="icon-share-alt small-125"></i>
  </a>

  <h3 class="header smaller lighter green"></h3>                    

<%= render 'form' %>



</div>

app/views/tickets/show.html.erb
<div class="breadcrumbs" id="breadcrumbs">
  <ul class="breadcrumb">
    <li>
      <i class="icon-home home-icon"></i>
      <%= link_to "活动管理", activities_path %>

      <span class="divider">
        <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>
    <li>
      <i class="icon-home home-icon"></i>
      <%= link_to @activity.name, @activity %>
      <span class="divider">
        <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>

    <li>
      <i class="icon-home home-icon"></i>
      <%= link_to "奖券", activity_tickets_path(@activity) %>
      <span class="divider">
        <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>

    <li class="active">
      <%= @ticket.uid%>
    </li>
  </ul>
</div>

<div class="page-content">

  <a href="<%= activity_tickets_path(@activity) %>" class="btn btn-app btn-pink btn-mini">
    <i class="icon-share-alt small-125"></i>
  </a>

  <a href="<%= edit_ticket_path(@ticket) %>
    " class="btn btn-app btn-primary  btn-mini">
    <i class="icon-edit small-125"></i>
  </a>

  <h3 class="header smaller lighter green"></h3>                    


  <p>
    <strong>唯一编号:</strong>
    <%= @ticket.uid %>
  </p>

  <p>
    <strong>获得者:</strong>
    <%= @ticket.consumer_id %>
  </p>

  <p>
    <strong>奖品:</strong>
    <%= @ticket.reward.name %>
  </p>

  <p>
    <strong>是否使用:</strong>
    <%= @ticket.is_used %>
  </p>

  <p>
    <strong>使用时间:</strong>
    <%= @ticket.used_time %>
  </p>





</div>