config/routes.rb
Lottery::Application.routes.draw do
  
  resources :orders

  resources :consumers

  resources :tickets

  resources :bussinesses

  resources :rewards
  
  resources :activities do
    resources :rewards
    resources :tickets
  end

  devise_for :users, :controllers => { :sessions => "sessions" }

  get '/consumer/login', to: 'consumer/sessions#create'
  get '/consumer/logout', to: 'consumer/sessions#destroy'
  get '/consumer/buy', to: 'consumer/orders#create'
  get '/consumer/exchange', to: 'consumer/tickets#exchange'
  get '/consumer/activities', to: 'consumer/activities#index'
  get '/consumer/change_profile', to: 'consumer/consumers#update'
  get '/consumer/lottery', to: 'consumer/tickets#lottery'
  get '/consumer/tickets', to: 'consumer/tickets#index'
  get '/consumer/buy_lottery', to: 'consumer/consumers#buy_lottery_count'
  get '/consumer/lottery_count', to: 'consumer/consumers#lottery_count'

  root :to => "welcome#index"
  
end

app/models/activity.rb
class Activity < ActiveRecord::Base

  belongs_to :user
  has_many :rewards

  has_many :orders

  NET = 1

  CALLS = 2

  SMS = 3

  CONSUME = [
    {id: NET, name: '网络流量'},
    {id: CALLS, name: '话费'},
    {id: SMS, name: '短信'}
  ]

  def date_range_str
    if self.start_time and self.end_time
      "#{self.start_time} - #{self.end_time}"
    else
      ""  
    end
  end

  def author_name
    self.user.name || "匿名"
  end

  def count_net 
    orders.where(consume_type: NET).count(:consume_amount)
  end

  def count_calls
    orders.where(consume_type: CALLS).count(:consume_amount)
  end

  def count_sms
    orders.where(consume_type: SMS).count(:consume_amount)
  end

  def info
    {id: id, name: name, description: content, awards: rewards.map {|r| r.photo_url.url} }
  end

  def lottery(consumer)

    award = rewards.map do |reward|
      p reward.rate
      if random_event_100(reward.rate)
        p "get rewards"
        reward
      else
        p "no rewards"
        nil  
      end
    end.compact().first()


    transaction() {  

      if award
        ticket = Ticket.create!(consumer: consumer, activity: self, reward: award)  
      else
        ticket = nil        
      end
      
      consumer.lottery_count -= 1
      consumer.save!

      Order.create!(consumer: consumer, activity: self, ticket: ticket)
      return ticket
    }
  end

  def random_event_100(rate)
    if rand(100) <= rate
      true
    else
      false 
    end  
  end     

  class << self
    
    def effective
      where("end_time > ? and start_time < ? ", Date.today, Date.today)
    end

  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  before_action :set_date_range, only: [:create, :update]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @orders = @activity.orders
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
    @activity.user = current_user
    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render action: 'show', status: :created, location: @activity }
      else
        format.html { render action: 'new' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :content, :start_time, :end_time, :author, :published)
    end

    def set_date_range
      start_time, end_time = params[:date_range].split('-')
      params[:activity][:start_time] = start_time
      params[:activity][:end_time] = end_time
      p activity_params
    end
end

app/controllers/consumer/activities_controller.rb
class Consumer::ActivitiesController < Consumer::ApplicationController

  before_filter :authenticate_consumer!

  def index
    @activities = Activity.effective
    render json: {activities: @activities.map {|a| a.info } }
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/consumer/activities_helper.rb
module Consumer::ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= content_for :head do %>
<link rel="stylesheet" href="/assets/css/jquery-ui-1.10.3.custom.min.css">
<link rel="stylesheet" href="/assets/css/chosen.css">
<link rel="stylesheet" href="/assets/css/datepicker.css">
<link rel="stylesheet" href="/assets/css/bootstrap-timepicker.css">
<link rel="stylesheet" href="/assets/css/daterangepicker.css">
<link rel="stylesheet" href="/assets/css/colorpicker.css">

<script src="/assets/js/jquery-ui-1.10.3.custom.min.js"></script>
<script src="/assets/js/jquery.ui.touch-punch.min.js"></script>
<script src="/assets/js/chosen.jquery.min.js"></script>
<script src="/assets/js/fuelux/fuelux.spinner.min.js"></script>
<script src="/assets/js/date-time/bootstrap-datepicker.min.js"></script>
<script src="/assets/js/date-time/bootstrap-timepicker.min.js"></script>
<script src="/assets/js/date-time/moment.min.js"></script>
<script src="/assets/js/date-time/daterangepicker.min.js"></script>
<script src="/assets/js/bootstrap-colorpicker.min.js"></script>
<script src="/assets/js/jquery.knob.min.js"></script>
<script src="/assets/js/jquery.autosize-min.js"></script>
<script src="/assets/js/jquery.inputlimiter.1.3.1.min.js"></script>
<script src="/assets/js/jquery.maskedinput.min.js"></script>
<script src="/assets/js/bootstrap-tag.min.js"></script>

<script type="text/javascript">
    ready = function($){
          $('#id-date-range-picker-1').daterangepicker(
            {
              format: 'YYYY/MM/DD'
            }
          );
    }; 
    jQuery(ready);

    jQuery(function ($) {
      $(document).on('page:load', ready);  
    });
    


  </script>

<% end -%>

<div class="widget-box">
  <div class="widget-header">
    <h4>活动</h4>
  </div>

  <div class="widget-body">
    <div class="widget-main no-padding">
      <%= form_for(@activity) do |f| %>
      <!--<legend>Form</legend>
    -->
    <fieldset>
      <%= f.label :name, "主题" %>
      <%= f.text_field :name %>
      <!-- <span class="help-block">Example block-level help text here.</span>
    -->
    <%= f.label :content, "内容" %>
    <%= f.text_field :content %>
    <!-- <span class="help-block">Example block-level help text here.</span>
  -->
  <%= f.label :time, "时限" %>

  <span class="add-on"> <i class="icon-calendar"></i>
  </span>

  <input type="text" name="date_range" id="id-date-range-picker-1", value="<%= @activity.date_range_str %>" />

  <%#= f.label :start_time, "开始时间" %>
  <%#= f.date_select :start_time %>
  <!-- <span class="help-block">Example block-level help text here.</span>
-->
<%#= f.label :end_time, "结束时间" %>
<%#= f.date_select :end_time %>
<!--         <div class="row-fluid input-prepend">
<span class="add-on"> <i class="icon-calendar"></i>
</span>

<input class="span10" type="text" name="date-range-picker" id="id-date-range-picker-1"></div>
-->
<!-- <span class="help-block">Example block-level help text here.</span>
-->
<label class="pull-right">
<%= f.check_box :published %>
<span class="lbl">是否发布</span>
</label>

</fieldset>

<div class="form-actions center">
<button class="btn btn-small btn-success">
提交
<i class="icon-arrow-right icon-on-right bigger-110"></i>
</button>
</div>
<% end -%></div>
</div>
</div>

app/views/activities/edit.html.erb
<div class="breadcrumbs" id="breadcrumbs">
  <ul class="breadcrumb">
    <li>
      <i class="icon-home home-icon"></i>
      <%= link_to "活动管理", activities_path %>

      <span class="divider">
        <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>
    <li>
      <i class="icon-home home-icon"></i>
      <%= link_to @activity.name, @activity %>

      <span class="divider">
        <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>
    <li class="active">
      编辑
    </li>
  </ul>
</div>

<div class="page-content">

  <a href="<%= activities_path%>" class="btn btn-app btn-pink btn-mini">
    <i class="icon-share-alt small-125"></i>
  </a>

  <h3 class="header smaller lighter green"></h3>                    

<%= render 'form' %>



</div>

app/views/activities/index.html.erb
<div class="breadcrumbs" id="breadcrumbs">
  <ul class="breadcrumb">
    <li> <i class="icon-home home-icon"></i>
      <%= link_to "活动管理", activities_path%>
      <span class="divider"> <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>
    <li class="active">总览</li>
  </ul>
</div>

<div class="page-content">

  <a href="<%= new_activity_path %>
    " class="btn btn-app btn-primary no-radius btn-small">
    <i class="icon-edit small-125"></i>
    新活动
  </a>

  <h3 class="header smaller lighter green"></h3>

  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>名称</th>
        <th>内容</th>
        <th>开始日期</th>
        <th>结束日期</th>
        <th>创建者</th>
        <th>发布</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @activities.each do |activity| %>
      <tr>
        <td>
          <%= activity.name %></td>
        <td>
          <%= activity.content %></td>
        <td>
          <%= activity.start_time %></td>
        <td>
          <%= activity.end_time %></td>
        <td>
          <%= activity.author_name %></td>
        <td>
          <% if activity.published %>
            <span style="color:green"><%= activity.published.to_cn%></span>  
          <% else %>  
            <span style="color:red"><%= activity.published.to_cn%></span>  
          <% end -%>  
        </td>
        <td>
          <div class="hidden-phone visible-desktop btn-group">
            <a href="<%= activity_path(activity)%>" class="btn btn-mini btn-success">
              <i class="icon-ok bigger-120"></i>
            </a>

            <a href="<%= edit_activity_path(activity) %>" class="btn btn-mini btn-info">
              <i class="icon-edit bigger-120"></i>
            </a>

            <a href="<%= activity_rewards_path(activity) %>" class="btn btn-mini btn-purple">
              <i class="icon-cloud-upload bigger-120"></i>
            </a>

            <a href="<%= activity_tickets_path(activity)%>" class="btn btn-yellow btn-mini">
              <i class="icon-shopping-cart bigger-120"></i>
            </a>

            <%= link_to activity, method: :delete, :class => "btn btn-mini btn-danger", data: { confirm: '确定删除?' } do %> 
              <i class="icon-trash bigger-120"></i>
            <% end -%>
          </div>

        </td>
        <!-- <td>
        <%= link_to 'Show', activity %></td>
      -->
      <!-- <td>
      <%= link_to 'Edit', edit_activity_path(activity) %></td>
    -->
    <!-- <td>
    <%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  -->
  <!-- </tr>
  -->
  <% end %></tbody>
</table>

<br></div>

app/views/activities/new.html.erb
<div class="breadcrumbs" id="breadcrumbs">
  <ul class="breadcrumb">
    <li>
      <i class="icon-home home-icon"></i>
      <a href="#">活动管理</a>

      <span class="divider">
        <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>
    <li class="active">
      创建新活动
    </li>
  </ul>
</div>

<div class="page-content">

  <a href="<%= activities_path%>" class="btn btn-app btn-pink btn-mini">
    <i class="icon-share-alt small-125"></i>
  </a>

  <h3 class="header smaller lighter green"></h3>                    

<%= render 'form' %>



</div>

app/views/activities/show.html.erb
<div class="breadcrumbs" id="breadcrumbs">
  <ul class="breadcrumb">
    <li>
      <i class="icon-home home-icon"></i>
      <%= link_to "活动管理", activities_path %>
      <span class="divider">
        <i class="icon-angle-right arrow-icon"></i>
      </span>
    </li>
    <li class="active">
      <%= @activity.name%>
    </li>
  </ul>
</div>

<div class="page-content">

  <a href="<%= activities_path%>" class="btn btn-app btn-pink btn-mini">
    <i class="icon-share-alt small-125"></i>
  </a>

  <a href="<%= edit_activity_path(@activity) %>
    " class="btn btn-app btn-primary  btn-mini">
    <i class="icon-edit small-125"></i>
  </a>

  <a href="<%= activity_rewards_path(@activity) %>" class="btn btn-app btn-purple btn-mini">
      <i class="icon-cloud-upload small-125"></i>
  </a>

  <h3 class="header smaller lighter green"></h3>                    


  <p>
    <strong>名称:</strong>
    <%= @activity.name %>
  </p>

  <p>
    <strong>内容:</strong>
    <%= @activity.content %>
  </p>

  <p>
    <strong>时限:</strong>
    <%= @activity.start_time%> - <%= @activity.end_time %>
  </p>

  <p>
    <strong>发布:</strong>
    <%= @activity.published.to_cn %>
  </p>

  <p>
    <strong>创建者:</strong>
    <%= @activity.author_name %>
  </p>

  <p>
    <strong>消耗网络流量:</strong>
    <%= @activity.count_net %>
  </p>  

  <p>
    <strong>消耗短信:</strong>
    <%= @activity.count_calls %>
  </p>  

  <p>
    <strong>消耗话费:</strong>
    <%= @activity.count_sms %>
  </p>  

    <h3 class="header smaller lighter green"></h3>
  <h3>消费</h3>
  <table  class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>购买ID</th>
        <th>消费者</th>
        <th>奖券</th>
        <th>创建时间</th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.id%></td>
          <td><%= order.consumer.phone%></td>
          <td><%= order.ticket.uid%></td>
          <td><%= order.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>


</div>